F branch
EmiLoKiJu/Portfolio pull request #13
Opened 2023-03-29 16:03 UTC by EmiLoKiJu

Completed mobile version.

2023-03-29 21:15 UTC, Eternalgratis commented on index.html
> +            </form>
- Kindly remove the ul and li tags in the form. These are basically used as bullets to list items but in this case, you won't be needing them. The inputs field are enough

2023-03-29 21:35 UTC, Eternalgratis commented on stetics.css
> +}
- Please increase the width of the input field so its looks like the one in the Figma.

2023-03-29 21:37 UTC, Eternalgratis requested changes
# Status: Required Changes ♻️
Hi @EmiLoKiJu , 

Good job so far!
There are some issues that you still need to work on in order to go to the next project, but not to worry, you are almost there!

## Highlights
✅ You used the correct Gitflow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Required Changes ♻️
 Check the comments under the review. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise. **

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 21:47 UTC, EmiLoKiJu commented on stetics.css
> +}
![image](https://user-images.githubusercontent.com/84760694/228674971-1fd9ed28-3bf3-43d5-8fe8-8118c6c33b26.png)

Can you be more specific? I don't see any difference.

2023-03-29 21:47 UTC, EmiLoKiJu commented on stetics.css
> +}
@Eternalgratis

2023-03-30 14:11 UTC, gersonhiggins commented
![image](https://user-images.githubusercontent.com/128397949/228863389-99a93495-7a4f-4ba1-982e-0d5b25792c4d.png)
Would be nice to place images into a folder, cause work with a orderly repository would look better and make it easier to find thing on it.

2023-03-30 14:16 UTC, gersonhiggins commented on README.md
kindly add a descriptive introduccion about your project, so the people can see what this project about

2023-03-30 15:16 UTC, RaoAkif requested changes
## STATUS: REQUIRED CHANGES ♻️

Hi @EmiLoKiJu, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Required Changes ♻️
A Pull request should be descriptive. It should have:
1. a descriptive title telling you what changes are inside.
2. a short summary describing introduced changes in more detail.

![image](https://user-images.githubusercontent.com/61361037/228882117-e98489bf-24a8-4932-8f8d-126c8624e7d2.png)

These good practices become our habits to do clean work that results in good collaboration with other fellow developers. 

_Check the comments under the review._
<img src="https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966" />

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 16:10 UTC, EmiLoKiJu commented
@RaoAkif I just edited what you did request. Do you think is ok now?

Also, it says "request pending" in my dashboard, so I don't know if you were waiting for me to make the changes and then close the review, or if something else happened.

Have a nice day~

2023-03-30 16:44 UTC, huseyinbiyik approved these changes
Hi team,

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- Form works as intended 👍 
- Form validations added 👍 
- Linter set up well and checks pass 🟢
- PR description is descriptive 📝

## Optional suggestions
⚠️  Please use descriptive branch names. FBranch doesn't tell about anything about the feature you added on the branch. "setup-contact-from", and "contact-form" would be better naming. [Check](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) more to learn more about this.


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 16:50 UTC, merged